# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 77ffd7c4dba3c6d82f0f1d30508bd1c9aee2c4efdbd81cc84fb1c7dee153a621cdad0366f1a7fb64b50e6901a472a91deb555dc36c5c153e97ec51b29b7c4103

test:
  secret_key_base: 1986810f88394a6663762afffb129be0ab333155ff641804ef48a077fea898ed420219c59d8e3d7b47d4fed84bc0c3a958d512c9419fb14b516649290034aa42

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SONGBOOK_SECRET_KEY_BASE"] %>
